In [1]:
import pandas as pd
from queries import *

C:\Users\smaxbehr\AppData\Local\anaconda3\envs\testenv\lib\site-packages\thinc\neural\train.py:7: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  from .optimizers import Adam, linear_decay
C:\Users\smaxbehr\AppData\Local\anaconda3\envs\testenv\lib\site-packages\thinc\check.py:4: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  from collections import Sequence, Sized, Iterable, Callable
C:\Users\smaxbehr\AppData\Local\anaconda3\envs\testenv\lib\site-packages\plac_ext.py:6: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
C:\Users\smaxbehr\AppData\Local\anaconda3\envs\testenv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
#load the ontology from "./ontologies/" and perform reasoning
onto_name= "bascat_2024-10-30_1yrs _100_cleaned" #input name of the ontology

#perform reasoning, get dois from publications in the extended ontology
onto_pub_list,onto,df=reasoning_dois_onto(onto_name)

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)
 
display(df)

* Owlready2 * WARNING: DataProperty http://xmlns.com/foaf/0.1/name belongs to more than one entity types: [owl.AnnotationProperty, owl.DatatypeProperty]; I'm trying to fix it...
* Owlready2 * Running HermiT...
    java -Xmx4000M -cp C:\Users\smaxbehr\AppData\Local\anaconda3\envs\testenv\lib\site-packages\owlready2\hermit;C:\Users\smaxbehr\AppData\Local\anaconda3\envs\testenv\lib\site-packages\owlready2\hermit\HermiT.jar org.semanticweb.HermiT.cli.CommandLine -c -O -D -I file:///C:/Users/smaxbehr/AppData/Local/Temp/tmp6jawtcla
* Owlready2 * HermiT took 1035.1132164001465 seconds
* Owlready * Reparenting property.AFX_0000553: {property.AFX_0000354, owl.ObjectProperty} => {property.AFX_0000354}
* Owlready * Reparenting property.AFX_0002688: {owl.ObjectProperty, property.AFX_0002686} => {property.AFX_0002686}
* Owlready * Reparenting property.AFX_0002689: {owl.ObjectProperty, property.AFX_0002686} => {property.AFX_0002686}
* Owlready * Reparenting property.AFX_0000072: {owl.ObjectProperty, property.AFX_0002686} => {property.AFX_0002686}
* Owlready * Reparenting property.AFX_0002687: {owl.ObjectProperty, property.AFX_0002686} => {property.AFX_0002686}
* Owlready * Reparenting core.relatedMatch: {owl.ObjectProperty, owl.SymmetricProperty, core.related, core.mappingRelation} => {core.related, core.mappingRelation}
* Owlready * Reparenting core.narrowMatch: {owl.ObjectProperty, core.narrower, core.mappingRelation} => {core.narrower, core.mappingRelation}
* Owlready * Reparenting obo.RO_0002334: {owl.ObjectProperty, owl.TransitiveProperty, obo.RO_0002427} => {obo.RO_0002427}
* Owlready * Reparenting obo.RO_0002404: {owl.ObjectProperty, obo.BFO_0000062, obo.RO_0002427} => {obo.BFO_0000062, obo.RO_0002427}
* Owlready * Reparenting obo.RO_0002081: {owl.ObjectProperty, obo.RO_0002222} => {obo.RO_0002222}
* Owlready * Reparenting obo.RO_0002088: {owl.ObjectProperty, obo.RO_0002222} => {obo.RO_0002222}
* Owlready * Reparenting obo.RO_0002223: {owl.ObjectProperty, obo.RO_0002222, obo.BFO_0000050} => {obo.RO_0002222, obo.BFO_0000050}
* Owlready * Reparenting obo.RO_0002086: {owl.ObjectProperty, owl.TransitiveProperty, obo.RO_0002222} => {owl.TransitiveProperty, obo.RO_0002222}
* Owlready * Reparenting obo.RO_0002084: {owl.ObjectProperty, obo.RO_0002222} => {obo.RO_0002222}
* Owlready * Reparenting obo.RO_0002089: {owl.ObjectProperty, owl.TransitiveProperty, obo.RO_0002222} => {owl.TransitiveProperty, obo.RO_0002222}
* Owlready * Reparenting obo.RO_0002230: {owl.ObjectProperty, obo.BFO_0000051, owl.TransitiveProperty, obo.RO_0002222} => {obo.BFO_0000051, obo.RO_0002222}
* Owlready * Reparenting obo.RO_0002229: {owl.ObjectProperty, obo.RO_0002222, obo.BFO_0000050} => {obo.RO_0002222, obo.BFO_0000050}
* Owlready * Reparenting property.AFX_0000558: {owl.ObjectProperty, property.AFX_0000331} => {property.AFX_0000331}
* Owlready * Reparenting property.AFX_0000557: {owl.ObjectProperty, property.AFX_0000331} => {property.AFX_0000331}
* Owlready * Reparenting property.AFX_0002731: {owl.ObjectProperty, property.AFX_0000388} => {property.AFX_0000388}
* Owlready * Reparenting obo.RO_0002524: {obo.RO_0002526, owl.ObjectProperty, obo.RO_0002522, obo.BFO_0000051, owl.TransitiveProperty} => {obo.RO_0002522, obo.BFO_0000051, obo.RO_0002526}
* Owlready * Reparenting obo.RO_0002525: {obo.RO_0002526, owl.ObjectProperty, obo.BFO_0000050, obo.RO_0002523, owl.TransitiveProperty} => {obo.RO_0002526, obo.BFO_0000050, obo.RO_0002523}
* Owlready * Reparenting obo.RO_0002411: {owl.ObjectProperty, obo.BFO_0000063, obo.RO_0002418} => {obo.BFO_0000063, obo.RO_0002418}
* Owlready * Reparenting obo.RO_0002090: {owl.ObjectProperty, obo.BFO_0000063} => {obo.BFO_0000063}
* Owlready * Reparenting obo.RO_0002012: {owl.ObjectProperty, obo.RO_0002418, obo.BFO_0000050} => {obo.RO_0002418, obo.BFO_0000050}
* Owlready * Reparenting obo.RO_0002305: {obo.RO_0002411, owl.ObjectProperty} => {obo.RO_0002411}
* Owlready * Reparenting obo.RO_0002304: {obo.RO_0002411, owl.ObjectProperty} => {obo.RO_0002411}
* Owlready * Reparenting obo.RO_0002082: {owl.ObjectProperty, obo.RO_0002081, owl.TransitiveProperty} => {obo.RO_0002081, owl.TransitiveProperty}
* Owlready * Reparenting obo.RO_0002083: {owl.ObjectProperty, obo.RO_0002081, owl.TransitiveProperty} => {obo.RO_0002081, owl.TransitiveProperty}
* Owlready * Reparenting obo.RO_0002507: {owl.ObjectProperty, obo.RO_0002559, obo.BFO_0000050, obo.RO_0002509} => {obo.RO_0002559, obo.BFO_0000050, obo.RO_0002509}
* Owlready * Reparenting obo.RO_0002529: {owl.ObjectProperty, owl.TransitiveProperty, obo.RO_0002527} => {owl.TransitiveProperty, obo.RO_0002527}
* Owlready * Reparenting obo.RO_0002515: {owl.ObjectProperty, obo.RO_0002527} => {obo.RO_0002527}
* Owlready * Reparenting property.AFX_0002724: {owl.ObjectProperty, property.AFX_0002723} => {property.AFX_0002723}
* Owlready * Reparenting obo.RO_0002501: {owl.ObjectProperty, obo.RO_0002410, owl.TransitiveProperty} => {obo.RO_0002410, owl.TransitiveProperty}
* Owlready * Reparenting obo.RO_0002595: {owl.ObjectProperty, obo.RO_0002410} => {obo.RO_0002410}
* Owlready * Reparenting obo.RO_0002506: {owl.ObjectProperty, obo.RO_0002410} => {obo.RO_0002410}
* Owlready * Reparenting obo.RO_0003302: {owl.ObjectProperty, obo.RO_0002410} => {obo.RO_0002410}
* Owlready * Reparenting obo.BFO_0000185: {owl.ObjectProperty, obo.BFO_0000067, owl.InverseFunctionalProperty} => {obo.BFO_0000067, owl.InverseFunctionalProperty}
* Owlready * Reparenting obo.RO_0002336: {owl.ObjectProperty, obo.RO_0002334} => {obo.RO_0002334}
* Owlready * Reparenting obo.RO_0002335: {owl.ObjectProperty, obo.RO_0002334} => {obo.RO_0002334}
* Owlready * Reparenting obo.RO_0002339: {owl.ObjectProperty, obo.RO_0002344} => {obo.RO_0002344}
* Owlready * Reparenting obo.RO_0002338: {owl.ObjectProperty, obo.RO_0002344} => {obo.RO_0002344}
* Owlready * Reparenting obo.RO_0002342: {owl.ObjectProperty, obo.RO_0002344} => {obo.RO_0002344}
* Owlready * Reparenting obo.RO_0002351: {owl.AsymmetricProperty, owl.ObjectProperty, property.AFX_0002793, owl.IrreflexiveProperty} => {owl.AsymmetricProperty, property.AFX_0002793, owl.IrreflexiveProperty}
* Owlready * Reparenting property.AFX_0000365: {owl.ObjectProperty, property.AFX_0002793} => {property.AFX_0002793}
* Owlready * Reparenting property.AFX_0002832: {owl.ObjectProperty, property.AFX_0002793} => {property.AFX_0002793}
* Owlready * Reparenting core.exactMatch: {owl.ObjectProperty, owl.SymmetricProperty, owl.TransitiveProperty, core.closeMatch} => {core.closeMatch, owl.TransitiveProperty}
* Owlready * Reparenting obo.RO_0002509: {owl.ObjectProperty, obo.RO_0002131, obo.RO_0002506} => {obo.RO_0002506, obo.RO_0002131}
* Owlready * Reparenting obo.BFO_0000184: {owl.ObjectProperty, obo.BFO_0000066, owl.InverseFunctionalProperty} => {obo.BFO_0000066, owl.InverseFunctionalProperty}
* Owlready * Reparenting obo.RO_0002500: {obo.RO_0002595, owl.ObjectProperty} => {obo.RO_0002595}
* Owlready * Reparenting obo.RO_0002584: {obo.RO_0002328, owl.ObjectProperty, obo.RO_0002595} => {obo.RO_0002595, obo.RO_0002328}
* Owlready * Reparenting property.AFX_0002801: {owl.ObjectProperty, property.AFX_0002803} => {property.AFX_0002803}
* Owlready * Reparenting property.AFX_0002696: {owl.ObjectProperty, property.AFX_0002803} => {property.AFX_0002803}
* Owlready * Reparenting property.AFX_0000834: {owl.ObjectProperty} => {property.AFX_0002802}
* Owlready * Reparenting obo.RO_0002221: {owl.ObjectProperty, obo.RO_0002220} => {obo.RO_0002220}
* Owlready * Reparenting property.AFX_0002846: {owl.ObjectProperty, obo.BFO_0000050} => {obo.BFO_0000050}
* Owlready * Reparenting property.AFX_0002833: {owl.ObjectProperty, property.AFX_0002858, owl.TransitiveProperty} => {property.AFX_0002858, owl.TransitiveProperty}
* Owlready * Reparenting obo.RO_0002344: {owl.ObjectProperty, obo.RO_0002337} => {obo.RO_0002337}
* Owlready * Reparenting obo.RO_0002341: {owl.ObjectProperty, obo.RO_0002337} => {obo.RO_0002337}
* Owlready * Reparenting obo.BFO_0000139: {obo.BFO_0000132, owl.ObjectProperty, owl.TransitiveProperty} => {obo.BFO_0000132}
* Owlready * Reparenting obo.BFO_0000138: {obo.BFO_0000132, owl.ObjectProperty, property.AFX_0002846, owl.TransitiveProperty} => {obo.BFO_0000132, property.AFX_0002846}
* Owlready * Reparenting property.AFX_0002836: {owl.ObjectProperty, property.AFX_0002834} => {property.AFX_0002834}
* Owlready * Reparenting obo.RO_0002410: {obo.RO_0002609, owl.ObjectProperty} => {obo.RO_0002609}
* Owlready * Reparenting obo.RO_0002610: {obo.RO_0002609, owl.ObjectProperty} => {obo.RO_0002609}
* Owlready * Reparenting property.AFX_0002723: {obo.RO_0002609, owl.ObjectProperty, owl.TransitiveProperty} => {obo.RO_0002609, owl.TransitiveProperty}
* Owlready * Reparenting obo.RO_0002087: {owl.ObjectProperty, obo.BFO_0000062} => {obo.BFO_0000062}
* Owlready * Reparenting obo.RO_0002002: {owl.ObjectProperty, obo.RO_0002323} => {obo.RO_0002323}
* Owlready * Reparenting obo.RO_0002177: {owl.ObjectProperty, obo.RO_0002323} => {obo.RO_0002323}
* Owlready * Reparenting obo.RO_0002176: {owl.ObjectProperty, obo.RO_0002323} => {obo.RO_0002323}
* Owlready * Reparenting obo.RO_0002163: {owl.ObjectProperty, obo.RO_0002323} => {obo.RO_0002323}
* Owlready * Reparenting obo.RO_0002000: {owl.ObjectProperty, obo.RO_0002323} => {obo.RO_0002323}
* Owlready * Reparenting obo.RO_0002170: {owl.ObjectProperty, obo.RO_0002323} => {obo.RO_0002323}
* Owlready * Reparenting obo.RO_0002131: {owl.ObjectProperty, obo.RO_0002323} => {obo.RO_0002323}
* Owlready * Reparenting obo.RO_0002150: {owl.ObjectProperty, obo.RO_0002323} => {obo.RO_0002323}
* Owlready * Reparenting property.AFX_0002717: {owl.ObjectProperty, obo.IAO_0000219} => {obo.IAO_0000219}
* Owlready * Reparenting property.AFX_0002819: {owl.ObjectProperty, obo.IAO_0000219} => {obo.IAO_0000219}
* Owlready * Reparenting obo.RO_0002517: {owl.ObjectProperty, owl.TransitiveProperty, obo.RO_0002524} => {obo.RO_0002524, obo.RO_0002525}
* Owlready * Reparenting obo.RO_0002220: {owl.ObjectProperty, obo.RO_0002163} => {obo.RO_0002163}
* Owlready * Reparenting obo.IAO_0000219: {owl.ObjectProperty, obo.IAO_0000136} => {obo.IAO_0000136}
* Owlready * Reparenting property.AFX_0000388: {owl.ObjectProperty, obo.IAO_0000136} => {obo.IAO_0000136}
* Owlready * Reparenting property.AFX_0002699: {owl.ObjectProperty, obo.IAO_0000136} => {obo.IAO_0000136}
* Owlready * Reparenting property.AFX_0002806: {owl.ObjectProperty, obo.IAO_0000136} => {obo.IAO_0000136}
* Owlready * Reparenting property.AFX_0000355: {owl.ObjectProperty, obo.IAO_0000136} => {obo.IAO_0000136}
* Owlready * Reparenting obo.OBI_0000314: {owl.ObjectProperty, property.AFX_0002821} => {property.AFX_0002821}
* Owlready * Reparenting obo.RO_0002327: {owl.ObjectProperty, obo.RO_0002215} => {obo.RO_0002215}
* Owlready * Reparenting obo.RO_0002530: {owl.ObjectProperty, obo.RO_0002515, obo.RO_0002529} => {obo.RO_0002515, obo.RO_0002529}
* Owlready * Reparenting property.AFX_0002835: {owl.ObjectProperty, property.AFX_0002833} => {property.AFX_0002833}
* Owlready * Reparenting property.AFX_0002878: {owl.ObjectProperty, property.AFX_0002730} => {property.AFX_0002730}
* Owlready * Reparenting core.topConceptOf: {owl.ObjectProperty, core.inScheme} => {core.inScheme}
* Owlready * Reparenting obo.RO_0002215: {owl.ObjectProperty, obo.RO_0002216} => {obo.RO_0002216}
* Owlready * Reparenting obo.RO_0002326: {owl.ObjectProperty, obo.RO_0002216} => {obo.RO_0002216}
* Owlready * Reparenting property.AFX_0000354: {owl.ObjectProperty, obo.RO_0000056} => {obo.RO_0000056}
* Owlready * Reparenting property.AFX_0002864: {owl.ObjectProperty, obo.RO_0000056} => {obo.RO_0000056}
* Owlready * Reparenting obo.RO_0002461: {owl.ObjectProperty, obo.RO_0000056} => {obo.RO_0000056}
* Owlready * Reparenting property.AFX_0002863: {owl.ObjectProperty, obo.RO_0000056} => {obo.RO_0000056}
* Owlready * Reparenting property.AFX_0000399: {owl.ObjectProperty, obo.RO_0000057} => {obo.RO_0000057}
* Owlready * Reparenting obo.RO_0002332: {owl.ObjectProperty, obo.RO_0000057} => {obo.RO_0000057}
* Owlready * Reparenting obo.RO_0002218: {owl.ObjectProperty, obo.RO_0000057} => {obo.RO_0000057}
* Owlready * Reparenting property.AFX_0002745: {owl.ObjectProperty, obo.RO_0000057} => {obo.RO_0000057}
* Owlready * Reparenting obo.RO_0002505: {owl.ObjectProperty, obo.RO_0000057} => {obo.RO_0000057}
* Owlready * Reparenting property.AFX_0002750: {owl.ObjectProperty, obo.RO_0000057} => {obo.RO_0000057}
* Owlready * Reparenting obo.RO_0002428: {owl.ObjectProperty, obo.RO_0002263, obo.RO_0002431} => {obo.RO_0002263, obo.RO_0002431}
* Owlready * Reparenting core.narrowerTransitive: {owl.ObjectProperty, owl.TransitiveProperty, core.semanticRelation} => {owl.TransitiveProperty, core.semanticRelation}
* Owlready * Reparenting core.mappingRelation: {owl.ObjectProperty, core.semanticRelation} => {core.semanticRelation}
* Owlready * Reparenting core.broaderTransitive: {owl.ObjectProperty, owl.TransitiveProperty, core.semanticRelation} => {owl.TransitiveProperty, core.semanticRelation}
* Owlready * Reparenting obo.RO_0002607: {owl.ObjectProperty, obo.RO_0002610} => {obo.RO_0002610}
* Owlready * Reparenting property.AFX_0002703: {obo.BFO_0000133, owl.ObjectProperty} => {obo.BFO_0000133}
* Owlready * Reparenting obo.RO_0002462: {owl.ObjectProperty, obo.RO_0002461} => {obo.RO_0002461}
* Owlready * Reparenting obo.RO_0002463: {owl.ObjectProperty, obo.RO_0002461} => {obo.RO_0002461}
* Owlready * Reparenting obo.RO_0003303: {owl.ObjectProperty, obo.RO_0003302} => {obo.RO_0003302}
* Owlready * Reparenting obo.RO_0003304: {owl.ObjectProperty, obo.RO_0003302} => {obo.RO_0003302}
* Owlready * Reparenting obo.RO_0002418: {obo.RO_0002501, owl.ObjectProperty, owl.TransitiveProperty} => {obo.RO_0002501}
* Owlready * Reparenting obo.RO_0002264: {owl.ObjectProperty, obo.RO_0002500} => {obo.RO_0002500}
* Owlready * Reparenting obo.RO_0002216: {obo.RO_0002328, owl.ObjectProperty, obo.RO_0002500} => {obo.RO_0002328, obo.RO_0002500}
* Owlready * Reparenting property.AFX_0002725: {owl.ObjectProperty, property.AFX_0002722} => {property.AFX_0002722}
* Owlready * Reparenting property.AFX_0000561: {owl.ObjectProperty, property.AFX_0000314} => {property.AFX_0000314}
* Owlready * Reparenting property.AFX_0000560: {owl.ObjectProperty, property.AFX_0000314} => {property.AFX_0000314}
* Owlready * Reparenting property.AFX_0000696: {owl.ObjectProperty, property.AFX_0000399} => {property.AFX_0000399}
* Owlready * Reparenting property.AFX_0002748: {owl.ObjectProperty, property.AFX_0000399} => {property.AFX_0000399}
* Owlready * Reparenting property.AFX_0002839: {owl.ObjectProperty, property.AFX_0002837} => {property.AFX_0002837}
* Owlready * Reparenting property.AFX_0002838: {owl.ObjectProperty, property.AFX_0002837} => {property.AFX_0002837}
* Owlready * Reparenting obo.RO_0002379: {owl.ObjectProperty, obo.RO_0002131} => {obo.RO_0002131}
* Owlready * Reparenting obo.RO_0002526: {owl.ObjectProperty, obo.RO_0002131, obo.RO_0002514} => {obo.RO_0002131, obo.RO_0002514}
* Owlready * Reparenting obo.RO_0002570: {owl.ObjectProperty, obo.RO_0002131} => {obo.RO_0002131}
* Owlready * Reparenting property.AFX_0002686: {owl.ObjectProperty, property.AFX_0002718} => {property.AFX_0002718}
* Owlready * Reparenting obo.RO_0002212: {owl.ObjectProperty, obo.RO_0002305, obo.RO_0002211} => {obo.RO_0002305, obo.RO_0002211}
* Owlready * Reparenting obo.RO_0002213: {owl.ObjectProperty, obo.RO_0002211, obo.RO_0002304} => {obo.RO_0002211, obo.RO_0002304}
* Owlready * Reparenting obo.RO_0002331: {owl.ObjectProperty, obo.RO_0002431} => {obo.RO_0002431}
* Owlready * Reparenting obo.RO_0000079: {owl.ObjectProperty, obo.RO_0000052} => {obo.RO_0000052}
* Owlready * Reparenting obo.RO_0000080: {owl.ObjectProperty, obo.RO_0000052} => {obo.RO_0000052}
* Owlready * Reparenting obo.RO_0002180: {owl.ObjectProperty, obo.BFO_0000051} => {obo.BFO_0000051}
* Owlready * Reparenting property.AFX_0002793: {owl.ObjectProperty, obo.BFO_0000051, owl.TransitiveProperty} => {obo.BFO_0000051}
* Owlready * Reparenting property.AFX_0000940: {owl.ObjectProperty, obo.BFO_0000051} => {obo.BFO_0000051}
* Owlready * Reparenting obo.RO_0002333: {obo.RO_0002328, owl.ObjectProperty} => {obo.RO_0002328}
* Owlready * Reparenting obo.RO_0002431: {obo.RO_0002328, owl.ObjectProperty, obo.RO_0002500, obo.RO_0002264} => {obo.RO_0002328, obo.RO_0002264}
* Owlready * Reparenting obo.RO_0002430: {owl.ObjectProperty, obo.RO_0002428} => {obo.RO_0002428}
* Owlready * Reparenting obo.RO_0002429: {owl.ObjectProperty, obo.RO_0002428} => {obo.RO_0002428}
* Owlready * Reparenting obo.RO_0000091: {owl.ObjectProperty, obo.RO_0000053} => {obo.RO_0000053}
* Owlready * Reparenting obo.RO_0000087: {owl.ObjectProperty, obo.RO_0000053} => {obo.RO_0000053}
* Owlready * Reparenting obo.RO_0002522: {owl.ObjectProperty, obo.RO_0002514, owl.TransitiveProperty} => {obo.RO_0002514, owl.TransitiveProperty}
* Owlready * Reparenting obo.RO_0002523: {owl.ObjectProperty, obo.RO_0002514, owl.TransitiveProperty} => {obo.RO_0002514, owl.TransitiveProperty}
* Owlready * Reparenting obo.RO_0002527: {owl.ObjectProperty, owl.SymmetricProperty, obo.RO_0002514} => {owl.SymmetricProperty, obo.RO_0002514}
* Owlready * Reparenting property.AFX_0002690: {owl.ObjectProperty, property.AFX_0002684} => {property.AFX_0002684}
* Owlready * Reparenting property.AFX_0002718: {owl.ObjectProperty, property.AFX_0002684} => {property.AFX_0002684}
* Owlready * Reparenting core.broader: {owl.ObjectProperty, core.broaderTransitive} => {core.broaderTransitive}
* Owlready * Reparenting obo.RO_0002371: {owl.ObjectProperty, owl.SymmetricProperty, obo.RO_0002177, obo.RO_0002170} => {obo.RO_0002170, owl.SymmetricProperty, obo.RO_0002177}
* Owlready * Reparenting obo.RO_0002263: {owl.ObjectProperty, obo.RO_0002264} => {obo.RO_0002264}
* Owlready * Reparenting property.AFX_0000551: {owl.AsymmetricProperty, owl.ObjectProperty, owl.IrreflexiveProperty, obo.RO_0002351} => {obo.RO_0002351}
* Owlready * Reparenting property.AFX_0002734: {owl.ObjectProperty, property.AFX_0000353} => {property.AFX_0000353}
* Owlready * Reparenting property.AFX_0002816: {property.AFX_0002699, owl.ObjectProperty} => {property.AFX_0002699}
* Owlready * Reparenting property.AFX_0002845: {owl.ObjectProperty, property.AFX_0002846} => {property.AFX_0002846}
* Owlready * Reparenting property.AFX_0002847: {owl.ObjectProperty, property.AFX_0002846} => {property.AFX_0002846}
* Owlready * Reparenting obo.OBI_0000645: {owl.ObjectProperty, property.AFX_0002846, owl.TransitiveProperty} => {property.AFX_0002846}
* Owlready * Reparenting property.AFX_0002800: {owl.ObjectProperty, property.AFX_0002846, owl.TransitiveProperty} => {property.AFX_0002846}
* Owlready * Reparenting property.AFX_0002722: {owl.ObjectProperty, obo.RO_0002502, owl.TransitiveProperty} => {obo.RO_0002502, owl.TransitiveProperty}
* Owlready * Reparenting obo.RO_0002503: {owl.ObjectProperty, obo.RO_0002502} => {obo.RO_0002502}
* Owlready * Reparenting obo.RO_0002314: {owl.ObjectProperty, obo.RO_0002502} => {obo.RO_0002502}
* Owlready * Reparenting property.AFX_0001179: {owl.ObjectProperty, obo.RO_0002170} => {obo.RO_0002170}
* Owlready * Reparenting property.AFX_0001178: {owl.ObjectProperty, obo.RO_0002170} => {obo.RO_0002170}
* Owlready * Reparenting obo.BFO_0000077: {owl.ObjectProperty, obo.BFO_0000057} => {obo.BFO_0000057}
* Owlready * Reparenting property.AFX_0000974: {owl.ObjectProperty, owl.TransitiveProperty, property.AFX_0000972} => {property.AFX_0000972}
* Owlready * Reparenting property.AFX_0001732: {owl.DatatypeProperty, property.AFX_0000690} => {property.AFX_0000690}
* Owlready * Reparenting property.AFX_0000671: {owl.DatatypeProperty, property.AFX_0000670} => {property.AFX_0000670}
* Owlready * Reparenting property.AFX_0000672: {owl.DatatypeProperty, property.AFX_0000670} => {property.AFX_0000670}
* Owlready * Reparenting property.AFX_0002861: {owl.DatatypeProperty, property.AFX_0000671} => {property.AFX_0000671}

The bascat_2024-10-30_1yrs _100_cleaned ontology consists of following publications:

,DOI,Title
0,10.1007/s10562-023-04527-4,Effect of a Second Promoter on the Performance of a Potassium Doped Silica-Supported Cobalt Catalyst During CO2 Hydrogenation to Hydrocarbons
1,10.1002/aic.18353,In situ DRIFTS examining the impact of indium doping on activity of CuIn/ZrO2 catalyst for CO2 hydrogenation to methanol
2,10.1007/s10562-022-04191-0,Investigation of In Promotion on Cu/ZrO2 Catalysts and Application in CO2 Hydrogenation to Methanol
3,10.1021/acs.accounts.4c00401,Small Molecule Activation at the acriPNP Pincer-Supported Nickel Sites
4,10.13226/j.issn.1006-6772.ZPF24041701,Co-thermal in situ hydrogenation of cement raw material to synthetic gas 水泥生料共热耦合原位加氢制合成气
5,10.1021/acscatal.3c01577,Efficient Conversion of Syngas into Ethanol by Tandem Catalysis
6,10.1016/j.apt.2024.104696,Combined (CO2 + CO) hydrogenation with methanolysis using aerosol metal-organic framework-derived hybrid catalysts
7,10.1002/adfm.202313886,Proton Turnover Dominated Cascade Route for CO2 Photoreduction
8,10.1016/j.apt.2024.104407,Gas-phase continuous synthesis of metal-organic framework-derived hybrid catalysts for combined CO2 and CO hydrogenation to methanol
9,10.1016/j.jece.2023.110331,An emerging and high-performance sepiolite-supported Ni catalyst for low-temperature CO2 methanation: The critical role of hydroxyl groups
10,10.1016/j.cej.2024.151198,"Enhancing methane formation in carbon dioxide hydrogenation on nickel clusters with zirconium additives: Exploring active sites, reaction pathways, and catalytic mechanisms"
11,10.1016/j.cej.2023.143428,Catalytic non-thermal milli-pulse plasma for methanation of CO2 without carbon deposition and catalyst deactivation
12,10.1021/acscatal.4c00742,Phosphorization-Induced “Fence Effect” on the Active Hydrogen Species Migration Enables Tunable CO2 Hydrogenation Selectivity
13,10.1016/j.cej.2022.140000,Boosting CO2-to-CO selectivity and durability by metal-support interaction and encapsulated effect of Ni@C capsules
14,10.3390/catal13020237,A Simple Strategy Stabilizing for a CuFe/SiO2 Catalyst and Boosting Higher Alcohols’ Synthesis from Syngas
15,10.1016/j.apenergy.2024.123247,Stable Cuδ+ species - Catalyzed CO₂ hydrogenation to methanol in silanol nests on Cu/S-1 catalyst
16,10.3390/molecules28186525,A Review of Theoretical Studies on Carbon Monoxide Hydrogenation via Fischer–Tropsch Synthesis over Transition Metals
17,10.1002/aic.18543,Tuning the CO2 hydrogenation activity and selectivity of TiO2 nanorods supported Rh catalyst via secondary-metals addition
18,10.1021/acscatal.3c00972,Efficient CO Electroreduction to Methanol by CuRh Alloys with Isolated Rh Sites
19,10.1016/j.eti.2023.103217,Unlocking the potential of CO2 hydrogenation into valuable products using noble metal catalysts: A comprehensive review
20,10.1021/acscatal.3c05939,Multiscale Investigation of the Mechanism and Selectivity of CO2 Hydrogenation over Rh(111)
21,10.1021/acscatal.3c03768,Tailoring the Near-Surface Environment of Rh Single-Atom Catalysts for Selective CO2 Hydrogenation
22,10.1039/d3cc90054a,Erratum: Controlling CO2 hydrogenation selectivity by Rh-based catalysts with different crystalline phases of TiO2 (Chemical Communications (2022) 58 (4219-4222) DOI: 10.1039/D2CC00472K)
23,10.1021/acscatal.4c01201,"Tuning Selectivity of CO2 Hydrogenation via Support Composition Modification Adjusted the Activity Reduction of H Species over Ce1-xPrxO2−δ-Supported Metal (Ru, Rh) Nanoclusters"
24,10.1016/j.jcou.2023.102621,Noble metal nanoparticles and nanodiamond modified strontium titanate photocatalysts for room temperature CO production from direct hydrogenation of CO2
25,10.1016/j.apsusc.2023.157873,Theoretical assessments of CO2 activation and hydrogenation pathways on transition-metal surfaces
26,10.1002/smm2.1201,Reduction-induced metal/oxide interfacial sites for selective CO2 hydrogenation
27,10.3390/catal13061014,Electrochemical Promotion of CO2 Hydrogenation Using Rh Catalysts Supported on O2− Conducting Solid Electrolyte
28,10.1021/acscatal.3c00512,Decoupling the Interfacial Catalysis of CeO2-Supported Rh Catalysts Tuned by CeO2 Morphology and Rh Particle Size in CO2 Hydrogenation
29,10.1021/acscatal.3c02534,"ZrO2-Promoted Cu-Co, Cu-Fe and Co-Fe Catalysts for Higher Alcohol Synthesis"
30,10.1039/d3cy01753b,Effect of Ni content on Cu-Mn/ZrO2 catalysts for methanol synthesis from CO2 hydrogenation
31,10.1021/acsaem.3c01373,Effect of Reflux Time on the Performance of the Cu/ZrO2 Catalyst for CO2 Hydrogenation to Methanol
32,10.1016/j.fuproc.2023.107789,Effect of Cu and Zn on the performance of Cu-Mn-Zn/ZrO2 catalysts for CO2 hydrogenation to methanol
33,10.1098/rsos.221213,Copper-doped ZnO-ZrO2solid solution catalysts for promoting methanol synthesis from CO2hydrogenation
34,10.1088/1361-6528/acc036,Ultra-thin ZrO2 overcoating on CuO-ZnO-Al2O3 catalyst by atomic layer deposition for improved catalytic performance of CO2 hydrogenation to dimethyl ether
35,10.1021/acs.joc.2c02179,Advancements and Challenges in Reductive Conversion of Carbon Dioxide via Thermo-/Photocatalysis
36,10.1016/j.cej.2024.149716,Kinetic and DRIFTS studies of the CO2 catalytic hydrogenation on Ru/SiO2: A comprehensive and strategic investigation of CO2 methanation mechanisms by kinetic modeling and data regression
37,10.1021/jacs.4c07502,Highly Selective Electrocatalytic CO2 Conversion to Tailored Products through Precise Regulation of Hydrogenation and C-C Coupling
38,10.1039/d4cc02073a,Mechanochemically-based three-way approach for the synthesis of K-doped Cu-Fe/ZnO-Al2O3 catalysts for converting CO2 to oxygenates
39,10.1016/j.mcat.2024.113949,Zn deposited nickel silicate nanotubes as efficient CO2 methanation catalysts
40,10.1016/j.cej.2024.148675,Catalytic reactivity of Pt sites for non-oxidative coupling of methane (NOCM)
41,10.1039/d3cy00014a,Hydrogen spillover effects in the Fischer-Tropsch reaction over carbon nanotube supported cobalt catalysts
42,10.1039/d2cy01721k,Photothermal steam reforming of methane over silica-supported nickel catalysts with temperature gradients
43,10.16084/j.issn1001-3555.2024.03.006,Preparation of Fly Ash-based Y-type Molecular Sieves and Their Performance for CO2 Hydrogenation 粉煤灰基 Y 型分子筛的制备及其对 CO2 加氢性能的研究
44,10.1016/j.jes.2023.08.028,Revealing the anti-sintering phenomenon on silica-supported nickel catalysts during CO2 hydrogenation
45,10.1002/smll.202308193,Single-Atom Ru Alloyed with Ni Nanoparticles Boosts CO2 Methanation
46,10.1016/j.enconman.2023.117811,Performance of Na-Ru/Al2O3 dual function material for integrated CO2 capture and methanation with the presence of coal ashes
47,10.1021/acsami.3c12413,Ni12P5 Confined in Mesoporous SiO2 with Near-Unity CO Selectivity and Enhanced Catalytic Activity for CO2 Hydrogenation
48,10.1016/j.jece.2024.113037,Analysis of the catalytic effects of silver and copper in the hydrogenation of dimethyl oxalate from a product perspective
49,10.1016/j.cej.2024.155624,Constructing stable Cu-Fe5C2 interfaces for efficient syngas conversion to higher alcohols
50,10.1021/acscatal.3c00074,K-ZrO2 Interfaces Boost CO2 Hydrogenation to Higher Alcohols
51,10.1016/j.apcatb.2024.123829,Tandemly coupled CO2 hydrogenation and carbonylation on SiO2-encapsulated Cu-ZnO nanoparticles with Ferrierite zeolite toward selective synthesis of oxygenates
52,10.1016/j.apcatb.2024.124065,Fine-tuning copper dispersion in Cu/SiO2 core-shell particles regulates electrochemical CO2 reduction product selectivity
53,10.1016/j.jaap.2024.106362,Study on free radical mechanism and experimental verification in biomass hydropyrolysis conversion to liquid fuels
54,10.19906/j.cnki.JFCT.2022085,CO2 hydrogenation to C5+ isoalkanes on ZnZr/HZSM-5 composite catalyst ZnZr/HZSM-5 复合催化剂上 CO2 加氢制备 C5+ 异构烷烃
55,10.1016/j.cej.2022.140565,Synergistic trimetallic Ni–Cu–Sn catalysts for efficient selective hydrogenation of phenylacetylene
56,10.1016/j.mcat.2023.113574,A dual-site Cu-ZnO/Cu@Si catalyst boosts CO2 hydrogenation to CH3OH
57,10.1016/S1872-5813(23)60382-2,Catalytic performance of La-modified Cu/SiO2 in the hydrogenation of methyl acetate 镧改性 Cu/SiO2 催化剂的乙酸甲酯高效加氢催化性能研究
58,10.1016/j.cherd.2024.02.035,Evaluation of the effect of methanol as an in-situ hydrogen source on the reduction of methyl acetate to ethanol
59,10.1016/j.mtcomm.2024.109569,Mechanistic study of TM/Mo6S8 catalysts boosts the ethanol synthesis from syngas
60,10.1021/acs.langmuir.4c01246,Electrochemical CO2 Reduction on Cu-Based Monatomic Alloys: A DFT Study
61,10.1016/j.mcat.2024.114035,Modulating selectivity in CO2 Methanation through Rhodium catalysts supported on Zirconia-Chemically grafted SBA-15
62,10.1021/acscatal.4c00339,Formation of (Rh-Fe)-FeOx Complex Sites Enables Methanol Synthesis from CO2
63,10.1039/d3sc01163a,The promotional role of Mn in CO2 hydrogenation over Rh-based catalysts from a surface organometallic chemistry approach
64,10.1021/acsanm.4c01298,Nickel Nanoparticles Supported on Lanthanum Oxycarbonate with Interfacial Oxygen Vacancies as Catalysts for CO2 Hydrogenation to Methane
65,10.1016/j.sajce.2023.01.002,Recent trend of metal promoter role for CO2 hydrogenation to C1 and C2+ products
66,10.1016/j.fuel.2022.126770,Synergetic effect of Ce/Zr for ethanol synthesis from syngas over Rh-based catalyst
67,10.1039/d3nh00506b,Mechanism of photocatalytic CO2 methanation on ultrafine Rh nanoparticles
68,10.1016/j.mcat.2024.114614,Characterization of NiFe alloy phases in nanoparticles used as selective catalysts for the production of furfuryl alcohol from furfural hydrogenation
69,10.1007/s42247-023-00598-6,"Efficient selective synthesis of furfuryl alcohol from furfural over non-noble metal supported on bio-waste rice husk-derived carbon, silica, and carbon silica catalysts"
70,10.1016/j.fuel.2022.126935,Porous SiO2 nanosphere-supported PtCuCo trimetallic nanoparticles for highly efficient and selective furfural hydrogenation
71,10.1016/S1872-5813(23)60362-7,Deactivation mechanism of Cu/SiO2 catalyst in gas phase hydrogenation of furfural to furfuryl alcohol 糠醛气相加氢制备糠醇 Cu/SiO2 催化剂的失活机理研究
72,10.1016/j.sajce.2024.08.003,The effect of zirconia as a promoter on Cu/MOF-5 catalysts for CO2 hydrogenation to methanol
73,10.1016/j.chemgeo.2024.122152,In situ investigation of the atomic structure of carbonate-silicate liquids at high pressure-temperature and spectroscopic characterization of the recovered quenched glasses
74,10.1002/cjce.24955,Cerium-promoted Ni/SiO2 catalyst for CO methanation
75,10.1016/j.jcat.2023.07.021,CO2 methanation with high-loading mesoporous Ni/SiO2 catalysts: Toward high specific activity and new mechanistic insights
76,10.1007/s11144-023-02377-0,The promotional effects of Mn on Ni/SiO2 catalysts for CO methanation
77,10.1016/j.jaap.2024.106718,Further research of the mechanism of char catalytic hydrogasification: Effect of spillover hydrogen on Fe-group catalysts
78,10.1016/j.fuel.2024.130939,Nickel catalyst supported on SiC incorporated SiO2 for CO2 methanation: Positive effects of dysprosium promoter and microwaves heating method
79,10.1002/ente.202201526,Promotion Effect of TiO2 on Ni/SiO2 Catalysts Prepared by Hydrothermal Method for CO2 Methanation
80,10.1016/j.fuel.2024.131998,Lanthanum-mediated enhancement of nickel nanoparticles for efficient CO2 methanation
81,10.1016/j.fuel.2023.128504,Direct synthesis of CH3OH from CO2 hydrogenation over Ni5Ga3/SiO2 catalysts
82,10.1002/cctc.202300572,Development and Up-scaling of Iron-based Catalysts for Fischer-Tropsch Synthesis of Higher Alcohols
83,10.1016/j.cattod.2022.07.014,Family of biomass-derived Ni and Ni–Mn catalysts of CO2 methanation
84,10.3103/S1061386223040131,Hydrogenation of CO2 on Co–Ni Catalysts Produced by Low-Temperature Combustion Using Modified Silica Fabric
85,10.1016/j.apsusc.2023.158945,Ni-noble metal bimetallic catalysts for improved low temperature CO2 methanation
86,10.1016/j.supflu.2023.106008,Nitrilethermal synthesis of CeO2-based composite nanoparticles as Ru and Pd catalyst supports for CO2 methanation and CH4 oxidation
87,10.1016/j.jcou.2023.102611,Selection and optimisation of a zeolite/catalyst mixture for sorption-enhanced CO2 methanation (SEM) process
88,10.1134/S0965544123090025,Hydrogenation of СО2 into Hydrocarbons on Bifunctional Catalysts
89,10.1002/anie.202401707,Active Oxygenated Structure-Intensified CO2 Capture Enables Efficient Electrochemical Ethylene Production Over Carbon Nanofibers
90,10.1016/j.poly.2024.117002,Nitrous oxide and dinitrogen complexes as intermediates in the decomposition of metal carbonyl nitrosyls: The triruthenium system
91,10.1007/s11164-023-05164-7,Cobalt supported on silica–alumina nanocomposite for use in CO2 methanation process: effects of Si/Al molar ratio and Co loading on catalytic activity
92,10.1016/j.cej.2022.139074,Selective C2 electrochemical synthesis from methane on modified alumina supporting single atom catalysts
93,10.1007/s10562-023-04554-1,Cu/ZnO/CeO2 Supported on MOF-5 as a Novel Catalyst for the CO2 Hydrogenation to Methanol: A Mechanistic Study on the Effect of CeO2 and MOF-5 on Active Sites
94,10.3390/ijms24087547,High-Loaded Copper-Containing Sol–Gel Catalysts for Furfural Hydroconversion
95,10.1016/j.apcata.2024.119727,"Structural study of mixed metal oxide catalysts comprising Mg, Ca, and Al used for upgrading biodiesel byproduct glycerol to glycerol carbonate"
96,10.1007/s11705-024-2448-7,Synthesis of tetrahedrally coordinated CoO for higher alcohol synthesis directly from syngas
97,10.1055/s-0040-1720121,"Recyclable Palladium-Catalyzed Carbonylative Coupling of Aryl Halides and Organoaluminum Compounds with tert -Butyl Iso cyanide as CO Equivalent Leading to 1,2-Diketones"
98,10.1021/acs.joc.2c01484,Synthesis of β-Lactams through Carbonylation of Diazo Compounds Followed by the [2 + 2] Cycloaddition Reaction
99,10.6023/cjoc202304016,"Synthesis and Propylene Oxide Carbonylation Hydroesterification Catalytic Property of N, O-Ligand Coordination Cobalt Compounds N, O-配体钴化合物的合成及其环氧丙烷羰化酯化的催化性能"

define DOI if only publications similar to specific publication in ontology should be queried from scopus\
if all publications in ontology should be used for query define the variable as:\
`doi = None`

In [ ]:
doi = r'10.1016/j.fuel.2023.127500'

Retrieve an abstract of the specific publication in the ontology given the DOI of the publication

In [ ]:
doi_1=r'10.1016/j.checat.2023.100584'
abstract=get_abstr(doi_1)

Following cells represent possible queries for reactions

- get list of all reactions for corresponding doi or from all publications if doi=None

In [ ]:
list_reac_doi,_ = get_reaction(reac=None,doi=doi,include_all=False) #doi=None (if from all publications)
reac_all = [*set([i[0].lower() for i in list_reac_doi])]
print(reac_all)

- get the list of all publications in ontology where same reactions as in input publication were mentioned

In [ ]:
list_reac_doi,_ = get_reaction(reac = None,doi = doi) #get list of all reactions mentioned in given doi (doi should be part of ontology)
same_reac_doi = []
for i in list_reac_doi:
    reac_doi,_ = get_reaction(reac = i[0],doi = None)
    for c in reac_doi:
        if c not in same_reac_doi and c[0] != doi:
            same_reac_doi.append(c)     #output example: [['10.1016/0304-5102(93)87113-m'],['10.1016/1381-1169(96)00243-9']]

print(list_reac_doi)
print(same_reac_doi)

- get the list of publications, that mention the specific reaction

In [ ]:
reac="hydrogenation"
list_reac_doi,_ = get_reaction(reac=reac,doi=None)  #output example: [['10.1016/0304-5102(93)87113-m'],['10.1016/1381-1169(96)00243-9']]
print(list_reac_doi)

- get list of all publications which mention the specific reaction and reactions which have this specific reaction as part of their label

In [ ]:
reac="hydroformylation" #specify a reaction

list_reac_doi, df_reac = get_reaction(reac="hydroformylation",doi=None, include_all=True)

display(df_reac)

- get list of all entities mentioned in specific publication

In [ ]:
list_ent=get_entList(list_type='all',entity= None,doi=doi)
print([i[1] for i in list_ent])

- get list of all extracted entities from publications in knowledge graph

In [ ]:
list_ent=[i[1] for i in get_entList(list_type='all',entity= None,doi=None)]
list_distinct=[]
for i in list_ent:
    if i not in list_distinct:
        list_distinct.append(i)
print(list_distinct)

In [ ]:
doi=None

In [ ]:
doi = "10.1021/acscatal.3c05579"

With following code the retrieval if all reactants, products, support materials, catalysts is performed, which are mentioned in one specific publication or from all publication in extended ontology (if doi=None) 
with `get_synonyms` all possible synonyms of chemical entities will be retrieved.\
For example from "rhodium atom " class, synonyms such as "Rh", "rhodium", "45Rh" are retrieved

In [ ]:
sup_list=get_support(sup=None,doi=doi)
_,sup_all=get_synonyms(sup_list)
print('all queried synonyms of support:')
print(list(sup_all.values()))

cat_list=get_catalyst(cat=None,doi=doi,include_all=True)
_,cat_all=get_synonyms(cat_list)
print('\nall queried synonyms of catalytic components:')
print(list(cat_all.values()))

reactant_list=get_entList('reactant',entity= None,doi=doi)
reactant_all,_=get_synonyms(reactant_list)
print('\nall queried synonyms of reactants:')
print(reactant_all)

product_list=get_entList('product',entity= None,doi=doi)
product_all,_=get_synonyms(product_list)
print('\nall queried synonyms of products:')
print(product_all)

cat_list_full=get_catalyst_full(doi = doi)
_,cat_full_all=get_synonyms(cat_list_full)
print('\nall queried catalyst entities:')
print(list(cat_full_all.values()))

### Iterate through all DOIs

In [3]:
def pad_list(data, target_len):
    #data_new = [x for x in data if onto_name not in x]
    data_new = [item for sublist in data for item in sublist if type(item) ==str]
    return list(set(data_new)) + [None] * (target_len - len(list(set(data_new))))

def list_len(data):
    data_new = [item for sublist in data for item in sublist if type(item) ==str]
    return len(list(set(data_new)))

df_all = pd.DataFrame()

for doi in df["DOI"]:

    if doi != "10.1016/j.mcat.2023.11327":

        sup_list=get_support(sup=None,doi=doi)
        _,sup_all=get_synonyms(sup_list)
        #  print('all queried synonyms of support:')
        #print(list(sup_all.values()))

        cat_list=get_catalyst(cat=None,doi=doi,include_all=True)
        _,cat_all=get_synonyms(cat_list)
        #  print('\nall queried synonyms of catalytic components:')
        #print(list(cat_all.values()))

        reactant_list=get_entList('reactant',entity= None,doi=doi)
        reactant_all,_=get_synonyms(reactant_list)
        #  print('\nall queried synonyms of reactants:')
        #print(reactant_all)

        product_list=get_entList('product',entity= None,doi=doi)
        product_all,_=get_synonyms(product_list)
        #  print('\nall queried synonyms of products:')
        #print(product_all)

        cat_list_full=get_catalyst_full(doi = doi)
        _,cat_full_all=get_synonyms(cat_list_full)
        #  print('\nall queried catalyst entities:')
        #  print(list(cat_full_all.values()))

        #max_len = max(len(list(sup_all.values())), len(list(cat_all.values())), len(reactant_all), len(product_all), len(list(cat_full_all.values())))
        max_len = max(list_len(sup_list), list_len(cat_list), list_len(reactant_list), list_len(product_list), list_len(cat_list_full))

        doi_extended = [doi] * max_len
        sup_extended = pad_list(sup_list, max_len)
        cat_extended = pad_list(cat_list, max_len)
        reactant_extended = pad_list(reactant_list, max_len)
        product_extended = pad_list(product_list, max_len)
        cat_full_extended = pad_list(cat_list_full, max_len)
        
        if doi == '10.1016/j.apcata.2024.119636':
            cat_full_ext_stor = cat_full_extended
            cat_list_full_stor = cat_list_full
        
        #if cat_full_extended != []:
        #    data_new = [x for x in cat_full_extended if onto_name not in x]

        df_out = pd.DataFrame({
            'doi': doi_extended,
            'catalyst with carrier': cat_full_extended,
            'support': sup_extended,
            'catalytic component': cat_extended,
            'reactant': reactant_extended,
            'product': product_extended        
        })

        df_all = pd.concat([df_all, df_out], axis = 0)

df_all

,doi,catalyst with carrier,support,catalytic component,reactant,product
0,10.1007/s10562-023-04527-4,15%Co-1%K supported on SiO2 catalyst,silicon dioxide,palladium,methane,hydrocarbon
1,10.1007/s10562-023-04527-4,None,15%Co-1%K supported on SiO2 catalyst,ruthenium atom,carbon monoxide,C5+ hydrocarbon
2,10.1007/s10562-023-04527-4,None,None,potassium atom,None,methane
3,10.1007/s10562-023-04527-4,None,None,"Ruthenium, palladium and copper",None,carbon monoxide
4,10.1007/s10562-023-04527-4,None,None,copper atom,None,None
5,10.1007/s10562-023-04527-4,None,None,carbon monoxide,None,None
6,10.1007/s10562-023-04527-4,None,None,silicon dioxide,None,None
0,10.1002/aic.18353,Cu supported on ZrO2 catalyst,Cu supported on ZrO2 catalyst,dioxozirconium,carbon monoxide,carbon monoxide
1,10.1002/aic.18353,CuIn supported on ZrO2 catalyst,CuIn supported on ZrO2 catalyst,copper atom,methanol,methanol
2,10.1002/aic.18353,CuIn0.05 supported on ZrO2 catalyst,dioxozirconium,zirconium atom,None,None
3,10.1002/aic.18353,None,CuIn0.05 supported on ZrO2 catalyst,copper;indium,None,None
4,10.1002/aic.18353,None,None,CuIn0.05,None,None
5,10.1002/aic.18353,None,None,carbon monoxide,None,None
6,10.1002/aic.18353,None,None,indium atom,None,None
0,10.1007/s10562-022-04191-0,Cu supported on ZrO2 catalyst,Cu supported on ZrO2 catalyst,dioxozirconium,carbon monoxide,carbon monoxide
1,10.1007/s10562-022-04191-0,None,dioxozirconium,copper atom,methanol,methanol
2,10.1007/s10562-022-04191-0,None,None,zirconium atom,None,None
3,10.1007/s10562-022-04191-0,None,None,carbon monoxide,None,None
4,10.1007/s10562-022-04191-0,None,None,CuZrIn5,None,None
5,10.1007/s10562-022-04191-0,None,None,indium atom,None,None
0,10.1021/acs.accounts.4c00401,nickel-containing metalloenzyme carbon monoxide dehydrogenase,nickel-containing metalloenzyme carbon monoxide dehydrogenase,Ile-Ile,carbon dioxide,organonitrogen compound oxime
1,10.1021/acs.accounts.4c00401,nickel(II supported on I supported on 0) complex,nickel(II supported on I supported on 0) complex,carbon monoxide,carbon monoxide,carbon dioxide
2,10.1021/acs.accounts.4c00401,None,nickel atom,nickel atom,None,carbon monoxide
3,10.1021/acs.accounts.4c00401,None,None,None,None,nitric oxide
0,10.13226/j.issn.1006-6772.ZPF24041701,None,None,iron atom,carbonate,methane
1,10.13226/j.issn.1006-6772.ZPF24041701,None,None,carbon monoxide,methane,carbon dioxide
2,10.13226/j.issn.1006-6772.ZPF24041701,None,None,None,carbon dioxide,carbon monoxide
3,10.13226/j.issn.1006-6772.ZPF24041701,None,None,None,carbon monoxide,None
0,10.1021/acscatal.3c01577,zeolite,None,zinc atom,methyl acetate,ethanol
1,10.1021/acscatal.3c01577,CuZnAlOx supported on γ-Al2O3,None,copper atom,carbon dioxide,carbon dioxide
2,10.1021/acscatal.3c01577,None,None,carbon monoxide,carbon monoxide,carbon monoxide
3,10.1021/acscatal.3c01577,None,None,aluminium atom,None,dimethyl ether
4,10.1021/acscatal.3c01577,None,None,Cu1Zn2AlOx,None,None
5,10.1021/acscatal.3c01577,None,None,CuZnAlOx,None,None
6,10.1021/acscatal.3c01577,None,None,γ-Al2O3,None,None
7,10.1021/acscatal.3c01577,None,None,zeolite,None,None
0,10.1016/j.apt.2024.104696,None,None,carbon monoxide,carbon dioxide,"3,5-dimethoxytoluene"
1,10.1016/j.apt.2024.104696,None,None,carbon atom,carbon monoxide,carbon dioxide
2,10.1016/j.apt.2024.104696,None,None,None,ethene,carbon monoxide
3,10.1016/j.apt.2024.104696,None,None,None,methanol,ethene
4,10.1016/j.apt.2024.104696,None,None,None,poly(ethylene terephthalate) polymer,methanol
0,10.1002/adfm.202313886,None,None,Cu1Ni5-TiO2,hydrogen atom,hydrogen atom
1,10.1002/adfm.202313886,None,None,copper atom,carbon dioxide,carbon dioxide
2,10.1002/adfm.202313886,None,None,CuxNiy,carbon monoxide,carbon monoxide
3,10.1002/adfm.202313886,None,None,carbon monoxide,methane,activated hydrogen
4,10.1002/adfm.202313886,None,None,nickel atom,None,methane
0,10.1016/j.apt.2024.104407,Cu-ZnO catalyst supported on either Al2O3 or CeO2,aluminium oxide,aluminium oxide,carbon dioxide,carbon dioxide
1,10.1016/j.apt.2024.104407,None,Cu-ZnO catalyst supported on either Al2O3 or CeO2,zinc oxide,carbon monoxide,carbon monoxide
2,10.1016/j.apt.2024.104407,None,ceric oxide,carbon monoxide,methanol,methanol
3,10.1016/j.apt.2024.104407,None,None,ceric oxide,None,None
0,10.1016/j.jece.2023.110331,10 wt% Ni supported on Sep,sepiolite,magnesium in Sep,methane,methane
1,10.1016/j.jece.2023.110331,clay mineral-supported Ni catalyst,sepiolite-supported Ni catalyst,carbon monoxide,carbon monoxide,carbon monoxide
2,10.1016/j.jece.2023.110331,sepiolite-supported Ni catalyst,O-phospho-L-serine,aluminium oxide,None,None
3,10.1016/j.jece.2023.110331,None,10 wt% Ni supported on Sep,nickel atom,None,None
0,10.1016/j.cej.2024.151198,0.5 wt% nickel (Ni) deposited supported on silica oxide support (SiO2),None,silica oxide,carbon monoxide,carbon monoxide
1,10.1016/j.cej.2024.151198,Ni catalyst,None,carbon monoxide,None,None
2,10.1016/j.cej.2024.151198,None,None,silicon dioxide,None,None
3,10.1016/j.cej.2024.151198,None,None,oxide,None,None
4,10.1016/j.cej.2024.151198,None,None,nickel atom,None,None
0,10.1016/j.cej.2023.143428,SiO2-supported catalyst,silicon dioxide,silicon dioxide,methane,methane
1,10.1016/j.cej.2023.143428,None,SiO2-supported catalyst,ruthenium atom,carbon dioxide,carbon dioxide
2,10.1016/j.cej.2023.143428,None,None,carbon monoxide,carbon monoxide,carbon monoxide
3,10.1016/j.cej.2023.143428,None,None,nickel atom,None,None
0,10.1021/acscatal.4c00742,Ru supported on SiO2 catalyst,silicon dioxide,silicon dioxide,methane,methane
1,10.1021/acscatal.4c00742,None,Ru supported on SiO2 catalyst,ruthenium atom,carbon monoxide,carbon monoxide
2,10.1021/acscatal.4c00742,None,None,carbon monoxide,None,None
0,10.1016/j.cej.2022.140000,Ni supported on C HCs,Ni supported on C HCs,NiCu3.8,methane,methane
1,10.1016/j.cej.2022.140000,NiCu3.8 supported on C hc,carbon atom,copper atom,carbon dioxide,carbon dioxide
2,10.1016/j.cej.2022.140000,None,None,carbon monoxide,carbon monoxide,carbon monoxide
3,10.1016/j.cej.2022.140000,None,None,carbon atom,None,None
4,10.1016/j.cej.2022.140000,None,None,nickel atom,None,None
0,10.3390/catal13020237,CuFe supported on SiO2 catalyst,silicon dioxide,iron atom,higher alcohol,carbon monoxide
1,10.3390/catal13020237,None,CuFe supported on SiO2 catalyst,copper;iron,carbon monoxide,hydrocarbon
2,10.3390/catal13020237,None,None,copper atom,direct CO,alcohol
3,10.3390/catal13020237,None,None,carbon monoxide,None,higher alcohol
4,10.3390/catal13020237,None,None,silicon dioxide,None,total alcohol
0,10.1016/j.apenergy.2024.123247,Cu supported on S-1,silicon dioxide,copper atom,carbon dioxide,carbon dioxide
1,10.1016/j.apenergy.2024.123247,Cu supported on S-1 catalyst,Cu supported on SiO2 catalyst,silicon dioxide,carbon monoxide,carbon monoxide
2,10.1016/j.apenergy.2024.123247,Cu supported on SiO2 catalyst,None,S-1,methanol,methanol
3,10.1016/j.apenergy.2024.123247,S-1 zeolite,None,carbon monoxide,None,None
0,10.3390/molecules28186525,Ru.,None,iron atom,hydrogen atom,hydrogen atom
1,10.3390/molecules28186525,None,None,rhodium atom,methane,methane
2,10.3390/molecules28186525,None,None,ruthenium atom,carbon monoxide,carbon monoxide
3,10.3390/molecules28186525,None,None,carbon monoxide,None,None
4,10.3390/molecules28186525,None,None,cobalt atom,None,None
5,10.3390/molecules28186525,None,None,nickel atom,None,None
0,10.1002/aic.18543,RhCu2.5 supported on TiO2),RhCu2.5 supported on TiO2),rhodium atom,methane,carbon monoxide
1,10.1002/aic.18543,RhMx supported on TiO2,titanium dioxide,titanium dioxide,carbon monoxide,alcohol
2,10.1002/aic.18543,TiO2 nanorod supported Rh catalyst,RhMx supported on TiO2,copper atom,methanol,methane
3,10.1002/aic.18543,None,TiO2 nanorod supported Rh catalyst,carbon monoxide,None,methanol
4,10.1002/aic.18543,None,None,cobalt atom,None,ethane
5,10.1002/aic.18543,None,None,RhMx,None,ethanol
6,10.1002/aic.18543,None,None,RhCu2.5,None,alkane
0,10.1021/acscatal.3c00972,Rh1Cu4 alloy,None,rhodium atom,carbon monoxide,carbon monoxide
1,10.1021/acscatal.3c00972,Rh1Cu4 catalyst,None,copper atom,methanol,methanol
2,10.1021/acscatal.3c00972,None,None,carbon monoxide,None,None
3,10.1021/acscatal.3c00972,None,None,Rh1Cu4,None,None
4,10.1021/acscatal.3c00972,None,None,carbon atom,None,None
0,10.1016/j.eti.2023.103217,None,None,oxide-zeolite,methane,dimethyl ether
1,10.1016/j.eti.2023.103217,None,None,carbon monoxide,carbon dioxide,carbon dioxide
2,10.1016/j.eti.2023.103217,None,None,OX-ZEO,carbon monoxide,carbon monoxide
3,10.1016/j.eti.2023.103217,None,None,carbon atom,methanol,methane
4,10.1016/j.eti.2023.103217,None,None,None,None,methanol
0,10.1021/acscatal.3c05939,Rh catalysts,None,rhodium atom,methane,methane
1,10.1021/acscatal.3c05939,Rh(111) facet,None,Rh(111),carbon monoxide,carbon monoxide
2,10.1021/acscatal.3c05939,None,None,carbon monoxide,None,None
0,10.1021/acscatal.3c03768,Rh1 supported on TiO2 catalysts with functionalized phosphonic acid monolayer,titanium dioxide,rhodium atom,methane,methane
1,10.1021/acscatal.3c03768,None,Rh1 supported on TiO2 catalysts with functionalized phosphonic acid monolayer,titanium dioxide,carbon monoxide,carbon monoxide
2,10.1021/acscatal.3c03768,None,None,phosphonic acid,None,None
3,10.1021/acscatal.3c03768,None,None,carbon monoxide,None,None
0,10.1039/d3cc90054a,1%Rh supported on p,phosphorus atom,rhodium atom,methane,methane
1,10.1039/d3cc90054a,Rh supported on a,1%Rh supported on p,carbon monoxide,carbon monoxide,carbon monoxide
2,10.1039/d3cc90054a,None,None,a,methanol,methanol
0,10.1021/acscatal.4c01201,"M supported on Ce1-xPrxO2-δ (M = Ru, Rh)",None,cerium,methane,methane
1,10.1021/acscatal.4c01201,None,None,rhodium atom,carbon monoxide,carbon monoxide
2,10.1021/acscatal.4c01201,None,None,ruthenium atom,None,None
3,10.1021/acscatal.4c01201,None,None,carbon monoxide,None,None
4,10.1021/acscatal.4c01201,None,None,Ce1-xPrxO2-δ,None,None
5,10.1021/acscatal.4c01201,None,None,M,None,None
0,10.1016/j.jcou.2023.102621,STO-ND-Ru sample,None,ruthenium atom,methane,methane
1,10.1016/j.jcou.2023.102621,None,None,STO-ND-Ru,carbon dioxide,carbon dioxide
2,10.1016/j.jcou.2023.102621,None,None,carbon monoxide,carbon monoxide,carbon monoxide
3,10.1016/j.jcou.2023.102621,None,None,None,photocatalytic CO2,None
0,10.1016/j.apsusc.2023.157873,None,None,rhodium atom,methane,methane
1,10.1016/j.apsusc.2023.157873,None,None,palladium,carbon dioxide,carbon dioxide
2,10.1016/j.apsusc.2023.157873,None,None,ruthenium atom,carbon monoxide,carbon monoxide
3,10.1016/j.apsusc.2023.157873,None,None,transition-metal,methanol,methanol
4,10.1016/j.apsusc.2023.157873,None,None,platinum,None,None
5,10.1016/j.apsusc.2023.157873,None,None,carbon monoxide,None,None
6,10.1016/j.apsusc.2023.157873,None,None,carbon atom,None,None
7,10.1016/j.apsusc.2023.157873,None,None,cobalt atom,None,None
8,10.1016/j.apsusc.2023.157873,None,None,nickel atom,None,None
0,10.1002/smm2.1201,InOx supported on Rh interface,rhodium atom,rhodium atom,methane,methane
1,10.1002/smm2.1201,Rh supported on CeO2,InOx supported on Rh interface,carbon monoxide,carbon monoxide,carbon monoxide
2,10.1002/smm2.1201,None,Rh supported on CeO2,ceric oxide,None,None
3,10.1002/smm2.1201,None,ceric oxide,(2R)-3-hydroxy-2-[(1R)-2-oxo-1-(6-oxo-1H-purin-9-yl)ethoxy]propanal,None,None
4,10.1002/smm2.1201,None,None,indium atom,None,None
0,10.3390/catal13061014,Rh catalyst electrode,None,rhodium atom,methane,methane
1,10.3390/catal13061014,None,None,carbon monoxide,carbon monoxide,carbon monoxide
0,10.1021/acscatal.3c00512,Rh particles,Rh supported on CeO2 catalyst,rhodium atom,methane,methane
1,10.1021/acscatal.3c00512,Rh supported on CeO2 catalyst,ceric oxide,carbon monoxide,carbon monoxide,carbon monoxide
2,10.1021/acscatal.3c00512,None,None,ceric oxide,None,None
0,10.1021/acscatal.3c02534,Co-Fe m-FTS,dioxozirconium,iron atom,carbon monoxide,carbon monoxide
1,10.1021/acscatal.3c02534,Co1Fe4 supported on ZrO2-10,Co1Fe4 supported on ZrO2-10,cobalt;copper,None,None
2,10.1021/acscatal.3c02534,ZrO2-free counterpart,ZrO2-free counterpart,dioxozirconium,None,None
3,10.1021/acscatal.3c02534,None,None,cobalt;iron,None,None
4,10.1021/acscatal.3c02534,None,None,copper atom,None,None
5,10.1021/acscatal.3c02534,None,None,zirconium atom,None,None
6,10.1021/acscatal.3c02534,None,None,carbon monoxide,None,None
7,10.1021/acscatal.3c02534,None,None,5-10 mol% ZrO2,None,None
8,10.1021/acscatal.3c02534,None,None,Cu1Co4,None,None
9,10.1021/acscatal.3c02534,None,None,cobalt atom,None,None
10,10.1021/acscatal.3c02534,None,None,"Cu:Co = 1:4, 5 mol% ZrO2",None,None
0,10.1039/d3cy01753b,CMNZ-0.01 catalyst,CuMn supported on ZrO2 catalyst,dioxozirconium,carbon dioxide,carbon dioxide
1,10.1039/d3cy01753b,Cu-MnNi supported on ZrO2 catalyst,Cu-MnNi supported on ZrO2 catalyst,manganese;nickel,methanol,methanol
2,10.1039/d3cy01753b,CuMn supported on ZrO2 catalyst,dioxozirconium,copper atom,None,None
3,10.1039/d3cy01753b,None,None,manganese atom,None,None
4,10.1039/d3cy01753b,None,None,zirconium atom,None,None
5,10.1039/d3cy01753b,None,None,cefmetazole sodium,None,None
6,10.1039/d3cy01753b,None,None,copper;manganese,None,None
7,10.1039/d3cy01753b,None,None,CMNZ-0.01,None,None
8,10.1039/d3cy01753b,None,None,nickel atom,None,None
0,10.1021/acsaem.3c01373,Cu supported on ZrO2 catalyst,Cu supported on ZrO2 catalyst,ZrO2-18h,methanol,methanol
1,10.1021/acsaem.3c01373,Cu supported on ZrO2-18h catalyst,dioxozirconium,copper atom,None,None
2,10.1021/acsaem.3c01373,None,None,zirconium atom,None,None
3,10.1021/acsaem.3c01373,None,None,dioxozirconium,None,None
0,10.1016/j.fuproc.2023.107789,Cu1.5Mn1.5O4 spinel,dioxozirconium,dioxozirconium,carbon dioxide,carbon dioxide
1,10.1016/j.fuproc.2023.107789,Cu-MnZn supported on ZrO2 catalyst,Cu-MnZn supported on ZrO2 catalyst,zinc atom,methanol,methanol
2,10.1016/j.fuproc.2023.107789,None,None,Cu1.5Mn1.5O4,None,None
3,10.1016/j.fuproc.2023.107789,None,None,copper atom,None,None
4,10.1016/j.fuproc.2023.107789,None,None,manganese;zinc,None,None
5,10.1016/j.fuproc.2023.107789,None,None,manganese atom,None,None
6,10.1016/j.fuproc.2023.107789,None,None,zirconium atom,None,None
7,10.1016/j.fuproc.2023.107789,None,None,Cu3MnZn0.5Zr0.5,None,None
0,10.1098/rsos.221213,None,None,zinc atom,methanol,methanol
1,10.1098/rsos.221213,None,None,copper atom,None,None
2,10.1098/rsos.221213,None,None,zirconium atom,None,None
3,10.1098/rsos.221213,None,None,copper;zinc;oxygen(2-);zirconium(4+),None,None
4,10.1098/rsos.221213,None,None,zinc;dioxido(oxo)zirconium,None,None
0,10.1088/1361-6528/acc036,bare CZA supported on HZSM-5 catalyst,None,zinc atom,None,dimethyl ether
1,10.1088/1361-6528/acc036,CuO-ZnO-Al2O3 (CZA) catalysts,None,copper atom,None,None
2,10.1088/1361-6528/acc036,HZSM-5 catalyst,None,aluminium atom,None,None
3,10.1088/1361-6528/acc036,None,None,dialuminum;zinc;oxocopper;oxygen(2-),None,None
4,10.1088/1361-6528/acc036,None,None,Zeolite Socony Mobil-5,None,None
5,10.1088/1361-6528/acc036,None,None,HZSM-5,None,None
0,10.1021/acs.joc.2c02179,None,None,carbon atom,carbon dioxide,alcohol
1,10.1021/acs.joc.2c02179,None,None,None,None,carbon dioxide
2,10.1021/acs.joc.2c02179,None,None,None,None,formic acid
0,10.1016/j.cej.2024.149716,Ru supported on SiO2 catalyst,silicon dioxide,silicon dioxide,methane,methane
1,10.1016/j.cej.2024.149716,None,Ru supported on SiO2 catalyst,ruthenium atom,None,None
0,10.1021/jacs.4c07502,electrocatalyst comprising Cu single atom and particle supported on CeO2,electrocatalyst comprising Cu single atom and particle supported on CeO2,copper atom,ethene,ethene
1,10.1021/jacs.4c07502,None,ceric oxide,ceric oxide,methane,methane
0,10.1039/d4cc02073a,multi-metallic K-doped CuFe supported on ZnO-Al2O3 catalyst,multi-metallic K-doped CuFe supported on ZnO-Al2O3 catalyst,iron atom,carbon dioxide,carbon dioxide
1,10.1039/d4cc02073a,None,zinc;oxido(oxo)alumane,zinc oxide,None,None
2,10.1039/d4cc02073a,None,copper;iron,potassium atom,None,None
3,10.1039/d4cc02073a,None,None,copper;iron,None,None
4,10.1039/d4cc02073a,None,None,aluminium oxide,None,None
5,10.1039/d4cc02073a,None,None,copper atom,None,None
0,10.1016/j.mcat.2024.113949,0.25Zn-NiSil catalyst,None,zinc atom,carbon dioxide,carbon dioxide
1,10.1016/j.mcat.2024.113949,nickel silicate nanotube,None,dioxido(oxo)silane;nickel(2+),methane,methane
2,10.1016/j.mcat.2024.113949,Ni and SiO2 containing catalyst,None,carbon atom,None,None
3,10.1016/j.mcat.2024.113949,nickel silicate (NiSil) nanotubes,None,silicon dioxide,None,None
4,10.1016/j.mcat.2024.113949,0.25Zn-NiSil sample,None,Zn-NiSil,None,None
5,10.1016/j.mcat.2024.113949,None,None,nickel atom,None,None
0,10.1016/j.cej.2024.148675,single atom Pt supported on CeO2 (Pt SAs) and Pt nanoparticle (∼2nm) supported on SiO2 (Pt np),silicon dioxide,silicon dioxide,ethene,hydrogen atom
1,10.1016/j.cej.2024.148675,None,ceric oxide,ceric oxide,methane,ethene
2,10.1016/j.cej.2024.148675,None,single atom Pt supported on CeO2 (Pt SAs) and Pt nanoparticle (∼2nm) supported on SiO2 (Pt np),platinum,hydrogen atom,methane
3,10.1016/j.cej.2024.148675,None,platinum,None,None,ethane
4,10.1016/j.cej.2024.148675,None,None,None,None,butene
5,10.1016/j.cej.2024.148675,None,None,None,None,propene
0,10.1039/d3cy00014a,pretreated carbon nanotube (CNT) supported cobalt catalyst,pretreated carbon nanotube (CNT) supported cobalt catalyst,cobalt atom,methane,methane
1,10.1039/d3cy00014a,SiO2-supported cobalt catalyst,SiO2-supported cobalt catalyst,silicon dioxide,None,None
2,10.1039/d3cy00014a,Co particle on cnt,silicon dioxide,carbon atom,None,None
3,10.1039/d3cy00014a,cobalt catalyst,carbon atom,None,None,None
0,10.1039/d2cy01721k,silica-supported nickel (Ni supported on SiO2) catalysts,silicon dioxide,water,methane,methane
1,10.1039/d2cy01721k,Ni supported on SiO2 catalyst,silica-supported nickel (Ni supported on SiO2) catalysts,silicon dioxide,hydrogen atom,hydrogen atom
2,10.1039/d2cy01721k,None,Ni supported on SiO2 catalyst,nickel atom,None,None
0,10.16084/j.issn1001-3555.2024.03.006,None,None,None,methane,methane
0,10.1016/j.jes.2023.08.028,1% Ni supported on SiO2 sample,silicon dioxide,silicon dioxide,carbon dioxide,carbon dioxide
1,10.1016/j.jes.2023.08.028,None,1% Ni supported on SiO2 sample,nickel atom,methane,methane
0,10.1002/smll.202308193,Ru1Ni supported on SiO2,silicon dioxide,silicon dioxide,carbon dioxide,carbon dioxide
1,10.1002/smll.202308193,None,Ru1Ni supported on SiO2,ruthenium atom,methane,methane
2,10.1002/smll.202308193,None,None,nickel;ruthenium,None,None
3,10.1002/smll.202308193,None,None,nickel atom,None,None
0,10.1016/j.enconman.2023.117811,Na-Ru supported on Al2O3 DFM,Na-Ru supported on Al2O3 DFM,sodium carbonate,carbonate,carbon dioxide
1,10.1016/j.enconman.2023.117811,Na2CO3 supported on γ-Al2O3,aluminium oxide,ruthenium atom,carbon dioxide,methane
2,10.1016/j.enconman.2023.117811,None,None,aluminium oxide,methane,dihydrogen
3,10.1016/j.enconman.2023.117811,None,None,aluminium atom,dihydrogen,None
4,10.1016/j.enconman.2023.117811,None,None,ferric oxide,None,None
5,10.1016/j.enconman.2023.117811,None,None,silicon dioxide,None,None
6,10.1016/j.enconman.2023.117811,None,None,γ-Al2O3,None,None
0,10.1021/acsami.3c12413,Ni12P5 supported on SBA-15,SiO2-supported Ni catalyst,nickel(2+);phosphorus(3-),methane,methane
1,10.1021/acsami.3c12413,SiO2-supported Ni catalyst,silicon dioxide,Ni12P5,None,None
2,10.1021/acsami.3c12413,nickel phosphide catalyst,None,SBA-15,None,None
3,10.1021/acsami.3c12413,Ni catalyst,None,nickel phosphide,None,None
4,10.1021/acsami.3c12413,None,None,silicon dioxide,None,None
5,10.1021/acsami.3c12413,None,None,nickel atom,None,None
0,10.1016/j.jece.2024.113037,None,None,zirconium atom,Methyl oxalate,ethene
1,10.1016/j.jece.2024.113037,None,None,dioxozirconium,ethene,methyl 2-hydroxyacetate
2,10.1016/j.jece.2024.113037,None,None,None,"5,5-dimethyloxazolidine-2,4-dione",None
0,10.1016/j.cej.2024.155624,Cu-Fe5C2 interface,silicon dioxide,iron atom,None,None

### Export

In [4]:
output_path='./output/output_BASCAT_2024-11-27.xlsx' #define the output path

df_all.to_excel(output_path)

## END

In [ ]:
sup_list=get_support(sup=None,doi=doi)
_,sup_all=get_synonyms(sup_list)
print('all queried synonyms of support:')
print(list(sup_all.values()))

In [ ]:
onto_pub_list

In [ ]:
sup_list=get_support(sup=None,doi=doi,only_doi= False)
sup_cat=[]
for i in range(len(sup_list)):
    sup_cat.append([sup_list[i][1],sup_list[i][2]])
print(sup_cat)

Perform a search in scopus using collected information from ontology\
Queries have following structure: 'TITLE-ABS-KEY("reaction"AND"catalyst"AND"support material"AND"reactant"AND"product")' in all possible combinations

In [ ]:
import pybliometrics
pybliometrics.scopus.init()

doi=None
df_all=scopus_seach_process(doi, onto_pub_list)

All distinct results are saved in sheet 'distinct_eid'.\
Filter found publication according to the start and end date\
If no filtering nessesary define `start_date` as follows:\
`get_synonyms = None`

In [ ]:
start_date = '2023-01-01'
end_date = '2024-12-31' 

distinct_df, filtered_df, filtered_df_doi, filtered_df_doi_new = filter_date(start_date,end_date, df_all,onto_pub_list)

save from scopus quieried publication information in Excel

In [ ]:
output_path='./output/output_bascat_2024-10-30_1yrs.xlsx' #define the output path

save_in_excel(output_path, df_all, distinct_df, filtered_df, filtered_df_doi, filtered_df_doi_new )